# Generated by Django 2.2.7 on 2020-01-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='number_bike',
            field=models.CharField(max_length=10000),
        ),
    ]
