# Generated by Django 3.0.3 on 2020-03-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='color_bike',
            field=models.CharField(choices=[('BLACK', 'Black'), ('RED', 'Red'), ('WHITE', 'White')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bike',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='number_bike',
            field=models.CharField(max_length=100),
        ),
    ]
