version: "3"
volumes:
  pgdata:

services:

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikes
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 8000:8000

  react:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    ports:
      - 3000:3000