version: '3'
volumes:
  pgdata:

services:
  python:
    build:
      context: .
      dockerfile: docker/Dockerfile
    #volumes:
    #- ./backend /backend
    ports:
    - 8000:8000

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikesDB
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432