# Generated by Django 3.0.3 on 2020-03-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_bike', models.CharField(max_length=10)),
                ('color_bike', models.CharField(choices=[('BLACK', 'Black'), ('RED', 'Red'), ('WHITE', 'White')], max_length=6)),
                ('is_free', models.BooleanField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
