# Generated by Django 2.2.7 on 2020-01-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_bike', models.IntegerField(default=-1)),
                ('color_bike', models.CharField(max_length=10)),
                ('is_free', models.BooleanField(default=True)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=128)),
                ('wallet', models.IntegerField(default=0)),
            ],
        ),
    ]
