# Generated by Django 3.0.3 on 2020-03-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_auto_20200314_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='color_bike',
            field=models.CharField(choices=[('BLACK', 'Black'), ('RED', 'Red'), ('WHITE', 'White')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bike',
            name='is_free',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='bike',
            name='number_bike',
            field=models.CharField(max_length=10),
        ),
    ]
