# Generated by Django 3.0.3 on 2020-03-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_auto_20200315_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='color_bike',
            field=models.CharField(choices=[('BLACK', 'Black'), ('RED', 'Red'), ('WHITE', 'White'), ('BLUE', 'Blue')], max_length=5),
        ),
    ]
