# Generated by Django 3.0.3 on 2020-03-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0007_auto_20200317_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
